title: "Damien Tan"
email: "dtjldamien@gmail.com"
description: "Damien Tan"
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: GFM
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Singapore

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Damien Tan"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "Hey there!"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dtjldamien"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# utterances
repository: "dtjldamien/dtjldamien.github.io"
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"
    label: "comment"
